### ISSUE TITLE
Language for field and lab experiments, surveys

### ISSUE THREAD

**Issue by bgreiner** [social-science-data-editors/template_README#14]
Hi,

The current README template seems to only cater to replication packages for papers that work with field data, but has no template content to describe specifics of lab or field experiments or surveys.

For lab and field experiments, we would typically ask for complete sets of experimental instructions, questionnaires, stimuli for all conditions, potentially screenshots, and for scripts for experimenters or research assistants, as well as for subject eligibility criteria (e.g. selection criteria, exclusions), recruitment waves, demographics of subject pool used. And for lab experiments specifically, we would further ask for a description of any pilot sessions/studies, and computer programs, configuration files, or scripts used to run the experiment. For surveys we will ask for the whole questionnaire including survey logic if not linear.

All these things should then also be linked and described in the template, such that the replicator knows where to find them and how they work together. 

At the moment, I do not have worked out any specific proposals for the text, though.

Cheers

/ben

**Comment by larsvilhuber** [comment]
Excellent points, probably reflecting the collective bias in the work of those that put it together. The AEA data and code policy explicitly defines these requirements, but the template does not have the language.

Two thoughts : 1, in the AEA policy we specifically require those elements in addition to the standard data processing instructions. Thus, conceptually, the entire data generation process you describe replaces/is the data provenance section, expanded.

2, I'm somewhat concerned not to conflict with the format that various registries (including the AEA registry) provide for such descriptions. The registration is required for AEA /field experiments, though not for lab experiments.

One solution might therefore be to piggy back on those for the template. "replace the data provenance section with the (extract of template from registry)".

The rest of the readme would remain the same.

Thoughts?

--
Sent from my mobile device
Lars Vilhuber

________________________________

**Comment by larsvilhuber** [comment]
@bgreiner I have added some language to address your comments ( 2411870 ) . Let me know if that gets at most of it. 

I have not yet addressed the desire to not duplicate existing information in registries. That might need to be a template sentence.

**Comment by bgreiner** [comment]
Thanks, Lars. This looks very good to me. 

I see the desire for not duplicating existing information in registries, but I note that 1) not all journals require pre-registration for all kinds of experiments or survey studies (e.g., as far I know, AER expects pre-registration for field experiments but not for lab experiments or survey data studies at the moment, other journals have no such requirements) and 2) information in registries often (or typically?) does not include experiment instructions, full questionnaires, and other details. 
One solution could be to add to the instructions above something like: "If any of this information has been provided in a pre-registration, then a link to that registration is sufficient."
