### ISSUE TITLE
Possibly align with the JASA form

### ISSUE THREAD

**Issue by larsvilhuber** [social-science-data-editors/template_README#15]
https://jasa-acs.github.io/repro-guide/pages/acc.html

**Comment by larsvilhuber** [comment]
@paciorek This ( 655a31b ) goes somewhat in the direction of your form, but some things simply do not line up well: the typical econ article uses between 4 - 30 datasets from various sources (and we want to know about those sources), and it is extremely rare to see the code run in less than a few hours - we do not assume it's a desktop machine. Let me know what you think.

**Comment by paciorek** [comment]
LGTM. No particular suggestions, but I'm glad it seems like our form was useful.

I like the presence of the various examples of how authors might respond. JASA might want to think more about whether we should do more of that.
