### ISSUE TITLE
Update CEA endorsement

### ISSUE THREAD

**Issue by larsvilhuber** [social-science-data-editors/template_README#19]
Peter (outgoing) endorsed, Marie (incoming) might also want to be added.

**Comment by larsvilhuber** [comment]
https://github.com/social-science-data-editors/template_README/blame/development/Endorsers.md#L14

**Comment by marieconnolly** [comment]
OK. C'est toi qui edit ? "assigned" ça veut dire que tu veux que je le fasse?

--
Marie Connolly
Professeure, Département des sciences économiques
Université du Québec à Montréal
C.P. 8888, Succ. Centre-ville
Montréal QC H3C 3P8

Téléphone : 514 987-3000 0277#
Fax : 514 987-8494
connolly.marie@uqam.ca<mailto:connolly.marie@uqam.ca>
http://www.connolly.uqam.ca/
http://grch.esg.uqam.ca/
________________________________

**Comment by larsvilhuber** [comment]
Ouaip.

--
Lars Vilhuber, Economist
Cornell University, Executive Director, Labor Dynamics Institute
  and ILR School - Department of Economics
American Economic Association - Data Editor
Journal of Privacy and Confidentiality - Managing Editor

lars.vilhuber@cornell.edu | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ldi@cornell.edu | +1.607-255-2744
________________________________
