### ISSUE TITLE
Replace "master" by "main"

### ISSUE THREAD

**Issue by kwenzig** [social-science-data-editors/template_README#20]
Perhaps it is a good idea to replace _master_ by _main_.

This topic is discussed here: https://www.wired.com/story/tech-confronts-use-labels-master-slave/

**Comment by larsvilhuber** [comment]
There is no master branch in this repository, nor is there a main branch.

**Comment by kwenzig** [comment]
The template suggests to use master.do-files.

Here is another report on this topic: https://www.washingtonpost.com/opinions/2020/06/12/tech-industry-has-an-ugly-master-slave-problem/

**Comment by larsvilhuber** [comment]
Thank you for clarifying. Must of the discussion has been about "master" branches. 

I do note that the particular problem is one of English language networking technology. 

I suggest making a pull request and clarifying that it is about the script to run all other scripts.
