### ISSUE TITLE
BUG: Link to Python example is broken.

### ISSUE THREAD

**Issue by chrisconlon** [social-science-data-editors/template_README#22]
https://pip.pypa.io/en/1.1/requirements/ 

gives a 404.

**Comment by andreamoro-git** [comment]
I was about to report the same

**Comment by larsvilhuber** [comment]
Thanks for reading, and catching. You would have hoped that having a version number in the URL has some permanence. Apparently not. 

I will replace with "https://pip.pypa.io/en/stable/user_guide/#ensuring-repeatability"
