### ISSUE TITLE
Data Citation link not working

### ISSUE THREAD

**Issue by femdias** [social-science-data-editors/template_README#49]
Hi,

Just letting you know that the link for the guide on Data Citations (https://social-science-data-editors.github.io/template_README/Data_citation_guidance.html, contained in the note of Data Availability and Provenance Statements part) is not working (Error 404, "File not found").

Thank you.

**Comment by larsvilhuber** [comment]
Thanks for letting us know @femdias

**Comment by larsvilhuber** [comment]
Deployed just now.
